# Part of Sweet Café Management. See LICENSE file for full copyright and licensing details.
from . import (
    sweet_branch,
    sweet_scrap_reason,
    sweet_scrap,
    hr_salary_scale,
    hr_employee,
    hr_contract,
    product_template,
    product_document,
    quotation_document,
    pos_config,
    pos_session,
    res_company,
    sweet_reservation,
    sweet_tax_bracket,
    sweet_onat_report,
    sweet_libro_igi,
    sweet_declaracion_anual,
)
